In [2]:
# Importing Pandas
import pandas as pd

## DataFrame Fundamentals

In [3]:
# Creating DataFrame
df = pd.DataFrame([[1,2], [3,4],[5,6]], columns= ['A','B'])

In [4]:
# Get bottom rows
df.tail(1)

   A  B
2  5  6

In [5]:
# Get columns and convert them to list
df.columns.tolist()

['A', 'B']

In [6]:
# Get information on dataframe
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
dtypes: int64(2)
memory usage: 180.0 bytes

In [7]:
# Get description on dataframe
df.describe()

         A    B
count  3.0  3.0
mean   3.0  4.0
std    2.0  2.0
min    1.0  2.0
25%    2.0  3.0
50%    3.0  4.0
75%    4.0  5.0
max    5.0  6.0

## Loading DataFrame from Files

In [8]:
# Reading data from CSV file
data= pd.read_csv('./DataSet/college_value_tableau_ready.csv')

In [9]:
# Get top 5 rows
data.head()

,UNITID,INSTNM,CITY,STABBR,ZIP,city_state_label,LATITUDE,LONGITUDE,institution_control_label,institution_control_order,...,admission_rate_percent,admission_rate_band,admission_rate_band_order,admission_rate_status,admission_rate_reported_100_flag,admission_rate_interpretation_note,sat_average_context,sat_average_status,sat_interpretation_note,admissions_profile_availability
0,100654,Alabama A & M University,Normal,AL,35762,"Normal, AL",34.783368,-86.568502,Public,1,...,57.95,More than 50% to 75%,3,Available,False,Admission rate describes institution-level adm...,938.0,Available,Average SAT score provides optional academic-p...,Both admission rate and SAT available
1,100663,University of Alabama at Birmingham,Birmingham,AL,35294-0110,"Birmingham, AL",33.505697,-86.799345,Public,1,...,88.18,More than 75% but below 100%,4,Available,False,Admission rate describes institution-level adm...,1258.0,Available,Average SAT score provides optional academic-p...,Both admission rate and SAT available
2,100690,Amridge University,Montgomery,AL,36117-3553,"Montgomery, AL",32.362609,-86.174010,Private nonprofit,2,...,NaN,Missing,6,Unavailable,NaN,Admission rate unavailable; the institution re...,NaN,Unavailable,SAT average unavailable; the institution remai...,Neither available
3,100706,University of Alabama in Huntsville,Huntsville,AL,35899,"Huntsville, AL",34.724557,-86.640449,Public,1,...,68.57,More than 50% to 75%,3,Available,False,Admission rate describes institution-level adm...,1319.0,Available,Average SAT score provides optional academic-p...,Both admission rate and SAT available
4,100724,Alabama State University,Montgomery,AL,36104-0271,"Montgomery, AL",32.364317,-86.295677,Public,1,...,97.55,More than 75% but below 100%,4,Available,False,Admission rate describes institution-level adm...,976.0,Available,Average SAT score provides optional academic-p...,Both admission rate and SAT available

In [10]:
# Fetching a column from df
data.CITY

0                 Normal
1             Birmingham
2             Montgomery
3             Huntsville
4             Montgomery
              ...
1929             Houston
1930          Chesapeake
1931       East Hartford
1932    Maryland Heights
1933       San Francisco
Name: CITY, Length: 1934, dtype: str

In [11]:
# Fetch rows using loc(column #, row #)
data.loc[3:9]

,UNITID,INSTNM,CITY,STABBR,ZIP,city_state_label,LATITUDE,LONGITUDE,institution_control_label,institution_control_order,...,admission_rate_percent,admission_rate_band,admission_rate_band_order,admission_rate_status,admission_rate_reported_100_flag,admission_rate_interpretation_note,sat_average_context,sat_average_status,sat_interpretation_note,admissions_profile_availability
3,100706,University of Alabama in Huntsville,Huntsville,AL,35899,"Huntsville, AL",34.724557,-86.640449,Public,1,...,68.57,More than 50% to 75%,3,Available,False,Admission rate describes institution-level adm...,1319.0,Available,Average SAT score provides optional academic-p...,Both admission rate and SAT available
4,100724,Alabama State University,Montgomery,AL,36104-0271,"Montgomery, AL",32.364317,-86.295677,Public,1,...,97.55,More than 75% but below 100%,4,Available,False,Admission rate describes institution-level adm...,976.0,Available,Average SAT score provides optional academic-p...,Both admission rate and SAT available
5,100751,The University of Alabama,Tuscaloosa,AL,35487-0100,"Tuscaloosa, AL",33.211875,-87.545978,Public,1,...,76.65,More than 75% but below 100%,4,Available,False,Admission rate describes institution-level adm...,1285.0,Available,Average SAT score provides optional academic-p...,Both admission rate and SAT available
6,100812,Athens State University,Athens,AL,35611,"Athens, AL",34.806793,-86.964698,Public,1,...,NaN,Missing,6,Unavailable,NaN,Admission rate unavailable; the institution re...,NaN,Unavailable,SAT average unavailable; the institution remai...,Neither available
7,100830,Auburn University at Montgomery,Montgomery,AL,36117-3596,"Montgomery, AL",32.367360,-86.177544,Public,1,...,91.57,More than 75% but below 100%,4,Available,False,Admission rate describes institution-level adm...,1093.0,Available,Average SAT score provides optional academic-p...,Both admission rate and SAT available
8,100858,Auburn University,Auburn,AL,36849,"Auburn, AL",32.599378,-85.488258,Public,1,...,45.92,More than 25% to 50%,2,Available,False,Admission rate describes institution-level adm...,1345.0,Available,Average SAT score provides optional academic-p...,Both admission rate and SAT available
9,101116,South University-Montgomery,Montgomery,AL,36116,"Montgomery, AL",32.342684,-86.216488,Private for-profit,3,...,NaN,Missing,6,Unavailable,NaN,Admission rate unavailable; the institution re...,NaN,Unavailable,SAT average unavailable; the institution remai...,Neither available

In [12]:
# Fetching a column using loc
data.loc[3:9, 'ZIP']

3         35899
4    36104-0271
5    35487-0100
6         35611
7    36117-3596
8         36849
9         36116
Name: ZIP, dtype: str

In [21]:
# Fetching multiple columns by loc
data.loc[3:12, ['INSTNM', 'admission_rate_band']]

                                 INSTNM           admission_rate_band
3   University of Alabama in Huntsville          More than 50% to 75%
4              Alabama State University  More than 75% but below 100%
5             The University of Alabama  More than 75% but below 100%
6               Athens State University                       Missing
7       Auburn University at Montgomery  More than 75% but below 100%
8                     Auburn University          More than 25% to 50%
9           South University-Montgomery                       Missing
10                  Faulkner University          More than 50% to 75%
11                   Huntingdon College          More than 50% to 75%
12        Heritage Christian University  More than 75% but below 100%

In [22]:
data.iloc[3:12, 0:2]

    UNITID                               INSTNM
3   100706  University of Alabama in Huntsville
4   100724             Alabama State University
5   100751            The University of Alabama
6   100812              Athens State University
7   100830      Auburn University at Montgomery
8   100858                    Auburn University
9   101116          South University-Montgomery
10  101189                  Faulkner University
11  101435                   Huntingdon College

In [35]:
# Accessing a single column
data.CITY

0                 Normal
1             Birmingham
2             Montgomery
3             Huntsville
4             Montgomery
              ...
1929             Houston
1930          Chesapeake
1931       East Hartford
1932    Maryland Heights
1933       San Francisco
Name: CITY, Length: 1934, dtype: str

In [40]:
# Sorting data dataframe
data.sort_values('ZIP')

,UNITID,INSTNM,CITY,STABBR,ZIP,city_state_label,LATITUDE,LONGITUDE,institution_control_label,institution_control_order,...,admission_rate_percent,admission_rate_band,admission_rate_band_order,admission_rate_status,admission_rate_reported_100_flag,admission_rate_interpretation_note,sat_average_context,sat_average_status,sat_interpretation_note,admissions_profile_availability
1607,242626,Inter American University of Puerto Rico-Aguad...,Aguadilla,PR,00603,"Aguadilla, PR",18.467886,-67.121671,Private nonprofit,2,...,41.76,More than 25% to 50%,2,Available,False,Admission rate describes institution-level adm...,NaN,Unavailable,SAT average unavailable; the institution remai...,Admission rate only
1614,243106,University of Puerto Rico-Aguadilla,Aguadilla,PR,00604-1309,"Aguadilla, PR",18.498652,-67.137930,Public,1,...,81.40,More than 75% but below 100%,4,Available,False,Admission rate describes institution-level adm...,909.0,Available,Average SAT score provides optional academic-p...,Both admission rate and SAT available
1608,242635,Inter American University of Puerto Rico-Arecibo,Arecibo,PR,00614,"Arecibo, PR",18.475090,-66.759010,Private nonprofit,2,...,38.20,More than 25% to 50%,2,Available,False,Admission rate describes institution-level adm...,NaN,Unavailable,SAT average unavailable; the institution remai...,Admission rate only
1615,243115,University of Puerto Rico-Arecibo,Arecibo,PR,00614-4010,"Arecibo, PR",18.469199,-66.741140,Public,1,...,59.18,More than 50% to 75%,3,Available,False,Admission rate describes institution-level adm...,NaN,Unavailable,SAT average unavailable; the institution remai...,Admission rate only
1600,241395,Pontifical Catholic University of Puerto Rico-...,Arecibo,PR,00614-4045,"Arecibo, PR",18.446006,-66.679114,Private nonprofit,2,...,93.78,More than 75% but below 100%,4,Available,False,Admission rate describes institution-level adm...,NaN,Unavailable,SAT average unavailable; the institution remai...,Admission rate only
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1538,236896,Walla Walla University,College Place,WA,99324-1198,"College Place, WA",46.048088,-118.389555,Private nonprofit,2,...,NaN,Missing,6,Unavailable,NaN,Admission rate unavailable; the institution re...,NaN,Unavailable,SAT average unavailable; the institution remai...,Neither available
1542,237057,Whitman College,Walla Walla,WA,99362,"Walla Walla, WA",46.069815,-118.331546,Private nonprofit,2,...,38.15,More than 25% to 50%,2,Available,False,Admission rate describes institution-level adm...,1410.0,Available,Average SAT score provides optional academic-p...,Both admission rate and SAT available
29,102553,University of Alaska Anchorage,Anchorage,AK,99508,"Anchorage, AK",61.190163,-149.826190,Public,1,...,NaN,Missing,6,Unavailable,NaN,Admission rate unavailable; the institution re...,NaN,Unavailable,SAT average unavailable; the institution remai...,Neither available
30,102580,Alaska Bible College,Palmer,AK,99645,"Palmer, AK",61.598553,-149.111972,Private nonprofit,2,...,NaN,Missing,6,Unavailable,NaN,Admission rate unavailable; the institution re...,NaN,Unavailable,SAT average unavailable; the institution remai...,Neither available
31,102614,University of Alaska Fairbanks,Fairbanks,AK,99775,"Fairbanks, AK",64.857560,-147.823146,Public,1,...,NaN,Missing,6,Unavailable,NaN,Admission rate unavailable; the institution re...,NaN,Unavailable,SAT average unavailable; the institution remai...,Neither available

In [42]:
# Looping through the dataframe
for index, row in data.iterrows():
    print(index)
    print(row)
    print('\n\n')

0
UNITID                                                                           100654
INSTNM                                                         Alabama A & M University
CITY                                                                             Normal
STABBR                                                                               AL
ZIP                                                                               35762
                                                            ...
admission_rate_interpretation_note    Admission rate describes institution-level adm...
sat_average_context                                                               938.0
sat_average_status                                                            Available
sat_interpretation_note               Average SAT score provides optional academic-p...
admissions_profile_availability                   Both admission rate and SAT available
Name: 0, Length: 70, dtype: object



1
UNITID                                                                           100663
INSTNM                                              University of Alabama at Birmingham
CITY                                                                         Birmingham
STABBR                                                                               AL
ZIP                                                                          35294-0110
                                                            ...
admission_rate_interpretation_note    Admission rate describes institution-level adm...
sat_average_context                                                              1258.0
sat_average_status                                                            Available
sat_interpretation_note               Average SAT score provides optional academic-p...
admissions_profile_availability                   Both admission rate and SAT available
Name: 1, Length: 70, dtype: object



2
UNITID                                                                           100690
INSTNM                                                               Amridge University
CITY                                                                         Montgomery
STABBR                                                                               AL
ZIP                                                                          36117-3553
                                                            ...
admission_rate_interpretation_note    Admission rate unavailable; the institution re...
sat_average_context                                                                 NaN
sat_average_status                                                          Unavailable
sat_interpretation_note               SAT average unavailable; the institution remai...
admissions_profile_availability                                       Neither available
Name: 2, Length: 70, dtype: object



3
UNITID                                                                           100706
INSTNM                                              University of Alabama in Huntsville
CITY                                                                         Huntsville
STABBR                                                                               AL
ZIP                                                                               35899
                                                            ...
admission_rate_interpretation_note    Admission rate describes institution-level adm...
sat_average_context                                                              1319.0
sat_average_status                                                            Available
sat_interpretation_note               Average SAT score provides optional academic-p...
admissions_profile_availability                   Both admission rate and SAT available
Name: 3, Length: 70, dtype: object



4
UNITID                                                                           100724
INSTNM                                                         Alabama State University
CITY                                                                         Montgomery
STABBR                                                                               AL
ZIP                                                                          36104-0271
                                                            ...
admission_rate_interpretation_note    Admission rate describes institution-level adm...
sat_average_context                                                               976.0
sat_average_status                                                            Available
sat_interpretation_note               Average SAT score provides optional academic-p...
admissions_profile_availability                   Both admission rate and SAT available
Name: 4, Length: 70, dtype: object



5
UNITID                                                                           100751
INSTNM                                                        The University of Alabama
CITY                                                                         Tuscaloosa
STABBR                                                                               AL
ZIP                                                                          35487-0100
                                                            ...
admission_rate_interpretation_note    Admission rate describes institution-level adm...
sat_average_context                                                              1285.0
sat_average_status                                                            Available
sat_interpretation_note               Average SAT score provides optional academic-p...
admissions_profile_availability                   Both admission rate and SAT available
Name: 5, Length: 70, dtype: object



6
UNITID                                                                           100812
INSTNM                                                          Athens State University
CITY                                                                             Athens
STABBR                                                                               AL
ZIP                                                                               35611
                                                            ...
admission_rate_interpretation_note    Admission rate unavailable; the institution re...
sat_average_context                                                                 NaN
sat_average_status                                                          Unavailable
sat_interpretation_note               SAT average unavailable; the institution remai...
admissions_profile_availability                                       Neither available
Name: 6, Length: 70, dtype: object



7
UNITID                                                                           100830
INSTNM                                                  Auburn University at Montgomery
CITY                                                                         Montgomery
STABBR                                                                               AL
ZIP                                                                          36117-3596
                                                            ...
admission_rate_interpretation_note    Admission rate describes institution-level adm...
sat_average_context                                                              1093.0
sat_average_status                                                            Available
sat_interpretation_note               Average SAT score provides optional academic-p...
admissions_profile_availability                   Both admission rate and SAT available
Name: 7, Length: 70, dtype: object



8
UNITID                                                                           100858
INSTNM                                                                Auburn University
CITY                                                                             Auburn
STABBR                                                                               AL
ZIP                                                                               36849
                                                            ...
admission_rate_interpretation_note    Admission rate describes institution-level adm...
sat_average_context                                                              1345.0
sat_average_status                                                            Available
sat_interpretation_note               Average SAT score provides optional academic-p...
admissions_profile_availability                   Both admission rate and SAT available
Name: 8, Length: 70, dtype: object



9
UNITID                                                                           101116
INSTNM                                                      South University-Montgomery
CITY                                                                         Montgomery
STABBR                                                                               AL
ZIP                                                                               36116
                                                            ...
admission_rate_interpretation_note    Admission rate unavailable; the institution re...
sat_average_context                                                                 NaN
sat_average_status                                                          Unavailable
sat_interpretation_note               SAT average unavailable; the institution remai...
admissions_profile_availability                                       Neither available
Name: 9, Length: 70, dtype: object



10
UNITID                                                                           101189
INSTNM                                                              Faulkner University
CITY                                                                         Montgomery
STABBR                                                                               AL
ZIP                                                                          36109-3390
                                                            ...
admission_rate_interpretation_note    Admission rate describes institution-level adm...
sat_average_context                                                              1020.0
sat_average_status                                                            Available
sat_interpretation_note               Average SAT score provides optional academic-p...
admissions_profile_availability                   Both admission rate and SAT available
Name: 10, Length: 70, dtype: object



11
UNITID                                                                           101435
INSTNM                                                               Huntingdon College
CITY                                                                         Montgomery
STABBR                                                                               AL
ZIP                                                                          36106-2148
                                                            ...
admission_rate_interpretation_note    Admission rate describes institution-level adm...
sat_average_context                                                              1142.0
sat_average_status                                                            Available
sat_interpretation_note               Average SAT score provides optional academic-p...
admissions_profile_availability                   Both admission rate and SAT available
Name: 11, Length: 70, dtype: object



12
UNITID                                                                           101453
INSTNM                                                    Heritage Christian University
CITY                                                                           Florence
STABBR                                                                               AL
ZIP                                                                          35630-9977
                                                            ...
admission_rate_interpretation_note    Admission rate describes institution-level adm...
sat_average_context                                                              1020.0
sat_average_status                                                            Available
sat_interpretation_note               Average SAT score provides optional academic-p...
admissions_profile_availability                   Both admission rate and SAT available
Name: 12, Length: 70, dtype: object



13
UNITID                                                                           101480
INSTNM                                                    Jacksonville State University
CITY                                                                       Jacksonville
STABBR                                                                               AL
ZIP                                                                               36265
                                                            ...
admission_rate_interpretation_note    Admission rate describes institution-level adm...
sat_average_context                                                              1059.0
sat_average_status                                                            Available
sat_interpretation_note               Average SAT score provides optional academic-p...
admissions_profile_availability                   Both admission rate and SAT available
Name: 13, Length: 70, dtype: object



14
UNITID                                                                           101587
INSTNM                                                       University of West Alabama
CITY                                                                         Livingston
STABBR                                                                               AL
ZIP                                                                               35470
                                                            ...
admission_rate_interpretation_note    Admission rate describes institution-level adm...
sat_average_context                                                              1015.0
sat_average_status                                                            Available
sat_interpretation_note               Average SAT score provides optional academic-p...
admissions_profile_availability                   Both admission rate and SAT available
Name: 14, Length: 70, dtype: object



15
UNITID                                                                           101675
INSTNM                                                                    Miles College
CITY                                                                          Fairfield
STABBR                                                                               AL
ZIP                                                                          35064-2621
                                                            ...
admission_rate_interpretation_note    Admission rate unavailable; the institution re...
sat_average_context                                                                 NaN
sat_average_status                                                          Unavailable
sat_interpretation_note               SAT average unavailable; the institution remai...
admissions_profile_availability                                       Neither available
Name: 15, Length: 70, dtype: object



16
UNITID                                                                           101693
INSTNM                                                             University of Mobile
CITY                                                                             Mobile
STABBR                                                                               AL
ZIP                                                                          36613-2842
                                                            ...
admission_rate_interpretation_note    Admission rate describes institution-level adm...
sat_average_context                                                              1220.0
sat_average_status                                                            Available
sat_interpretation_note               Average SAT score provides optional academic-p...
admissions_profile_availability                   Both admission rate and SAT available
Name: 16, Length: 70, dtype: object



17
UNITID                                                                           101709
INSTNM                                                         University of Montevallo
CITY                                                                         Montevallo
STABBR                                                                               AL
ZIP                                                                          35115-6000
                                                            ...
admission_rate_interpretation_note    Admission rate describes institution-level adm...
sat_average_context                                                                 NaN
sat_average_status                                                          Unavailable
sat_interpretation_note               SAT average unavailable; the institution remai...
admissions_profile_availability                                     Admission rate only
Name: 17, Length: 70, dtype: object



18
UNITID                                                                           101879
INSTNM                                                      University of North Alabama
CITY                                                                           Florence
STABBR                                                                               AL
ZIP                                                                          35632-0001
                                                            ...
admission_rate_interpretation_note    Admission rate describes institution-level adm...
sat_average_context                                                                 NaN
sat_average_status                                                          Unavailable
sat_interpretation_note               SAT average unavailable; the institution remai...
admissions_profile_availability                                     Admission rate only
Name: 18, Length: 70, dtype: object



19
UNITID                                                                           101912
INSTNM                                                               Oakwood University
CITY                                                                         Huntsville
STABBR                                                                               AL
ZIP                                                                               35896
                                                            ...
admission_rate_interpretation_note    Admission rate describes institution-level adm...
sat_average_context                                                                 NaN
sat_average_status                                                          Unavailable
sat_interpretation_note               SAT average unavailable; the institution remai...
admissions_profile_availability                                     Admission rate only
Name: 19, Length: 70, dtype: object



20
UNITID                                                                           102049
INSTNM                                                               Samford University
CITY                                                                         Birmingham

In [ ]:
# Filtering dataframe using columns
data.loc[data['admission_rate_status'] == 'Available', ['UNITID', 'CITY', 'ZIP']][0:10]

    UNITID        CITY         ZIP
0   100654      Normal       35762
1   100663  Birmingham  35294-0110
3   100706  Huntsville       35899
4   100724  Montgomery  36104-0271
5   100751  Tuscaloosa  35487-0100
7   100830  Montgomery  36117-3596
8   100858      Auburn       36849
10  101189  Montgomery  36109-3390
11  101435  Montgomery  36106-2148
12  101453    Florence  35630-9977

In [61]:
# Filtering dataframe using contains keyword
data[data['CITY'].str.contains('Mont')]

,UNITID,INSTNM,CITY,STABBR,ZIP,city_state_label,LATITUDE,LONGITUDE,institution_control_label,institution_control_order,...,admission_rate_percent,admission_rate_band,admission_rate_band_order,admission_rate_status,admission_rate_reported_100_flag,admission_rate_interpretation_note,sat_average_context,sat_average_status,sat_interpretation_note,admissions_profile_availability
2,100690,Amridge University,Montgomery,AL,36117-3553,"Montgomery, AL",32.362609,-86.174010,Private nonprofit,2,...,NaN,Missing,6,Unavailable,NaN,Admission rate unavailable; the institution re...,NaN,Unavailable,SAT average unavailable; the institution remai...,Neither available
4,100724,Alabama State University,Montgomery,AL,36104-0271,"Montgomery, AL",32.364317,-86.295677,Public,1,...,97.55,More than 75% but below 100%,4,Available,False,Admission rate describes institution-level adm...,976.0,Available,Average SAT score provides optional academic-p...,Both admission rate and SAT available
7,100830,Auburn University at Montgomery,Montgomery,AL,36117-3596,"Montgomery, AL",32.367360,-86.177544,Public,1,...,91.57,More than 75% but below 100%,4,Available,False,Admission rate describes institution-level adm...,1093.0,Available,Average SAT score provides optional academic-p...,Both admission rate and SAT available
9,101116,South University-Montgomery,Montgomery,AL,36116,"Montgomery, AL",32.342684,-86.216488,Private for-profit,3,...,NaN,Missing,6,Unavailable,NaN,Admission rate unavailable; the institution re...,NaN,Unavailable,SAT average unavailable; the institution remai...,Neither available
10,101189,Faulkner University,Montgomery,AL,36109-3390,"Montgomery, AL",32.384181,-86.216410,Private nonprofit,2,...,73.07,More than 50% to 75%,3,Available,False,Admission rate describes institution-level adm...,1020.0,Available,Average SAT score provides optional academic-p...,Both admission rate and SAT available
11,101435,Huntingdon College,Montgomery,AL,36106-2148,"Montgomery, AL",32.351034,-86.284366,Private nonprofit,2,...,69.49,More than 50% to 75%,3,Available,False,Admission rate describes institution-level adm...,1142.0,Available,Average SAT score provides optional academic-p...,Both admission rate and SAT available
17,101709,University of Montevallo,Montevallo,AL,35115-6000,"Montevallo, AL",33.106250,-86.865099,Public,1,...,53.85,More than 50% to 75%,3,Available,False,Admission rate describes institution-level adm...,NaN,Unavailable,SAT average unavailable; the institution remai...,Admission rate only
118,119058,Middlebury Institute of International Studies ...,Monterey,CA,93940,"Monterey, CA",36.599736,-121.897325,Private nonprofit,2,...,NaN,Missing,6,Unavailable,NaN,Admission rate unavailable; the institution re...,NaN,Unavailable,SAT average unavailable; the institution remai...,Neither available
845,185590,Montclair State University,Montclair,NJ,07043-1624,"Montclair, NJ",40.860414,-74.198141,Public,1,...,87.89,More than 75% but below 100%,4,Available,False,Admission rate describes institution-level adm...,1070.0,Available,Average SAT score provides optional academic-p...,Both admission rate and SAT available
1034,199032,Montreat College,Montreat,NC,28757-1267,"Montreat, NC",35.646577,-82.297600,Private nonprofit,2,...,69.20,More than 50% to 75%,3,Available,False,Admission rate describes institution-level adm...,NaN,Unavailable,SAT average unavailable; the institution remai...,Admission rate only
1257,214795,Pennsylvania State University-Penn State Mont ...,Mont Alto,PA,17237-9700,"Mont Alto, PA",39.842212,-77.541797,Public,1,...,98.21,More than 75% but below 100%,4,Available,False,Admission rate describes institution-level adm...,1160.0,Available,Average SAT score provides optional academic-p...,Both admission rate and SAT available