#### Importing Pandas

In [ ]:
import pandas as pd

#### DataFrame Fundamentals

In [2]:
# Creating DataFrame
df = pd.DataFrame([[1,2], [3,4],[5,6]], columns= ['A','B'])

In [3]:
# Get bottom rows
df.tail(1)

   A  B
2  5  6

In [4]:
# Get columns and convert them to list
df.columns.tolist()

['A', 'B']

In [5]:
# Get information on dataframe
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
dtypes: int64(2)
memory usage: 180.0 bytes

In [6]:
# Get description on dataframe
df.describe()

         A    B
count  3.0  3.0
mean   3.0  4.0
std    2.0  2.0
min    1.0  2.0
25%    2.0  3.0
50%    3.0  4.0
75%    4.0  5.0
max    5.0  6.0

#### Loading DataFrame from Files

In [7]:
# Reading data from CSV file
data= pd.read_csv('./DataSet/college_value_tableau_ready.csv')

In [8]:
# Get top 5 rows
data.head()

,UNITID,INSTNM,CITY,STABBR,ZIP,city_state_label,LATITUDE,LONGITUDE,institution_control_label,institution_control_order,campus_status_label,admission_rate_status,region_label,region_order,locale_type_label,locale_detailed_label,locale_detailed_order,undergraduate_enrollment_primary,undergraduate_enrollment_size_band
0,100654,Alabama A & M University,Normal,AL,35762,"Normal, AL",34.783368,-86.568502,Public,1,Main campus,Available,Southeast,5,City,City: Midsize,2,6124,"5,000 to 9,999"
1,100663,University of Alabama at Birmingham,Birmingham,AL,35294-0110,"Birmingham, AL",33.505697,-86.799345,Public,1,Main campus,Available,Southeast,5,City,City: Midsize,2,11635,"10,000 to 19,999"
2,100690,Amridge University,Montgomery,AL,36117-3553,"Montgomery, AL",32.362609,-86.174010,Private nonprofit,2,Main campus,Unavailable,Southeast,5,City,City: Midsize,2,241,"Fewer than 1,000"
3,100706,University of Alabama in Huntsville,Huntsville,AL,35899,"Huntsville, AL",34.724557,-86.640449,Public,1,Main campus,Available,Southeast,5,City,City: Midsize,2,6591,"5,000 to 9,999"
4,100724,Alabama State University,Montgomery,AL,36104-0271,"Montgomery, AL",32.364317,-86.295677,Public,1,Main campus,Available,Southeast,5,City,City: Midsize,2,3477,"1,000 to 4,999"

In [9]:
# Fetching a column from df
data.CITY

0                 Normal
1             Birmingham
2             Montgomery
3             Huntsville
4             Montgomery
              ...
1929             Houston
1930          Chesapeake
1931       East Hartford
1932    Maryland Heights
1933       San Francisco
Name: CITY, Length: 1934, dtype: str

In [10]:
# Fetch rows using loc(column #, row #)
data.loc[3:9]

,UNITID,INSTNM,CITY,STABBR,ZIP,city_state_label,LATITUDE,LONGITUDE,institution_control_label,institution_control_order,campus_status_label,admission_rate_status,region_label,region_order,locale_type_label,locale_detailed_label,locale_detailed_order,undergraduate_enrollment_primary,undergraduate_enrollment_size_band
3,100706,University of Alabama in Huntsville,Huntsville,AL,35899,"Huntsville, AL",34.724557,-86.640449,Public,1,Main campus,Available,Southeast,5,City,City: Midsize,2,6591,"5,000 to 9,999"
4,100724,Alabama State University,Montgomery,AL,36104-0271,"Montgomery, AL",32.364317,-86.295677,Public,1,Main campus,Available,Southeast,5,City,City: Midsize,2,3477,"1,000 to 4,999"
5,100751,The University of Alabama,Tuscaloosa,AL,35487-0100,"Tuscaloosa, AL",33.211875,-87.545978,Public,1,Main campus,Available,Southeast,5,City,City: Midsize,2,33227,"20,000 or more"
6,100812,Athens State University,Athens,AL,35611,"Athens, AL",34.806793,-86.964698,Public,1,Main campus,Unavailable,Southeast,5,Town,Town: Fringe,7,2446,"1,000 to 4,999"
7,100830,Auburn University at Montgomery,Montgomery,AL,36117-3596,"Montgomery, AL",32.367360,-86.177544,Public,1,Main campus,Available,Southeast,5,City,City: Midsize,2,2542,"1,000 to 4,999"
8,100858,Auburn University,Auburn,AL,36849,"Auburn, AL",32.599378,-85.488258,Public,1,Main campus,Available,Southeast,5,City,City: Small,3,26816,"20,000 or more"
9,101116,South University-Montgomery,Montgomery,AL,36116,"Montgomery, AL",32.342684,-86.216488,Private for-profit,3,Non-main campus,Unavailable,Southeast,5,City,City: Midsize,2,299,"Fewer than 1,000"

In [11]:
# Fetching a column using loc
data.loc[3:9, 'ZIP']

3         35899
4    36104-0271
5    35487-0100
6         35611
7    36117-3596
8         36849
9         36116
Name: ZIP, dtype: str

In [12]:
# Fetching multiple columns by loc
data.loc[3:12, ['INSTNM', 'CITY']]

                                 INSTNM        CITY
3   University of Alabama in Huntsville  Huntsville
4              Alabama State University  Montgomery
5             The University of Alabama  Tuscaloosa
6               Athens State University      Athens
7       Auburn University at Montgomery  Montgomery
8                     Auburn University      Auburn
9           South University-Montgomery  Montgomery
10                  Faulkner University  Montgomery
11                   Huntingdon College  Montgomery
12        Heritage Christian University    Florence

In [13]:
data.iloc[3:12, 0:2]

    UNITID                               INSTNM
3   100706  University of Alabama in Huntsville
4   100724             Alabama State University
5   100751            The University of Alabama
6   100812              Athens State University
7   100830      Auburn University at Montgomery
8   100858                    Auburn University
9   101116          South University-Montgomery
10  101189                  Faulkner University
11  101435                   Huntingdon College

In [14]:
# Accessing a single column
data.CITY

0                 Normal
1             Birmingham
2             Montgomery
3             Huntsville
4             Montgomery
              ...
1929             Houston
1930          Chesapeake
1931       East Hartford
1932    Maryland Heights
1933       San Francisco
Name: CITY, Length: 1934, dtype: str

In [15]:
# Sorting data dataframe
data.sort_values('ZIP')

,UNITID,INSTNM,CITY,STABBR,ZIP,city_state_label,LATITUDE,LONGITUDE,institution_control_label,institution_control_order,campus_status_label,admission_rate_status,region_label,region_order,locale_type_label,locale_detailed_label,locale_detailed_order,undergraduate_enrollment_primary,undergraduate_enrollment_size_band
1614,243106,University of Puerto Rico-Aguadilla,Aguadilla,PR,00604-1309,"Aguadilla, PR",18.498652,-67.137930,Public,1,Main campus,Available,Outlying Areas,9,Suburb,Suburb: Midsize,5,1883,"1,000 to 4,999"
1615,243115,University of Puerto Rico-Arecibo,Arecibo,PR,00614-4010,"Arecibo, PR",18.469199,-66.741140,Public,1,Main campus,Available,Outlying Areas,9,City,City: Small,3,2669,"1,000 to 4,999"
1600,241395,Pontifical Catholic University of Puerto Rico-...,Arecibo,PR,00614-4045,"Arecibo, PR",18.446006,-66.679114,Private nonprofit,2,Non-main campus,Available,Outlying Areas,9,Suburb,Suburb: Small,6,273,"Fewer than 1,000"
1595,241191,Universidad Adventista de las Antillas,Mayaguez,PR,00680-0000,"Mayaguez, PR",18.205685,-67.111207,Private nonprofit,2,Main campus,Available,Outlying Areas,9,Suburb,Suburb: Small,6,830,"Fewer than 1,000"
1627,243586,Pontifical Catholic University of Puerto Rico-...,Mayaguez,PR,00680-1713,"Mayaguez, PR",18.182375,-67.145695,Private nonprofit,2,Non-main campus,Available,Outlying Areas,9,City,City: Small,3,555,"Fewer than 1,000"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1538,236896,Walla Walla University,College Place,WA,99324-1198,"College Place, WA",46.048088,-118.389555,Private nonprofit,2,Main campus,Unavailable,Far West,8,Suburb,Suburb: Small,6,1252,"1,000 to 4,999"
1542,237057,Whitman College,Walla Walla,WA,99362,"Walla Walla, WA",46.069815,-118.331546,Private nonprofit,2,Main campus,Available,Far West,8,City,City: Small,3,1531,"1,000 to 4,999"
29,102553,University of Alaska Anchorage,Anchorage,AK,99508,"Anchorage, AK",61.190163,-149.826190,Public,1,Main campus,Unavailable,Far West,8,City,City: Large,1,7212,"5,000 to 9,999"
30,102580,Alaska Bible College,Palmer,AK,99645,"Palmer, AK",61.598553,-149.111972,Private nonprofit,2,Main campus,Unavailable,Far West,8,Suburb,Suburb: Small,6,24,"Fewer than 1,000"
31,102614,University of Alaska Fairbanks,Fairbanks,AK,99775,"Fairbanks, AK",64.857560,-147.823146,Public,1,Main campus,Unavailable,Far West,8,City,City: Small,3,4207,"1,000 to 4,999"

In [16]:
# Looping through the dataframe
for index, row in data.iterrows():
    print(index)
    print(row)
    print('\n\n')

0
UNITID                                                  100654
INSTNM                                Alabama A & M University
CITY                                                    Normal
STABBR                                                      AL
ZIP                                                      35762
city_state_label                                    Normal, AL
LATITUDE                                             34.783368
LONGITUDE                                           -86.568502
institution_control_label                               Public
institution_control_order                                    1
campus_status_label                                Main campus
admission_rate_status                                Available
region_label                                         Southeast
region_order                                                 5
locale_type_label                                         City
locale_detailed_label                            City: Midsize
locale_detailed_order                                        2
undergraduate_enrollment_primary                          6124
undergraduate_enrollment_size_band              5,000 to 9,999
Name: 0, dtype: object



1
UNITID                                                             100663
INSTNM                                University of Alabama at Birmingham
CITY                                                           Birmingham
STABBR                                                                 AL
ZIP                                                            35294-0110
city_state_label                                           Birmingham, AL
LATITUDE                                                        33.505697
LONGITUDE                                                      -86.799345
institution_control_label                                          Public
institution_control_order                                               1
campus_status_label                                           Main campus
admission_rate_status                                           Available
region_label                                                    Southeast
region_order                                                            5
locale_type_label                                                    City
locale_detailed_label                                       City: Midsize
locale_detailed_order                                                   2
undergraduate_enrollment_primary                                    11635
undergraduate_enrollment_size_band                       10,000 to 19,999
Name: 1, dtype: object



2
UNITID                                            100690
INSTNM                                Amridge University
CITY                                          Montgomery
STABBR                                                AL
ZIP                                           36117-3553
city_state_label                          Montgomery, AL
LATITUDE                                       32.362609
LONGITUDE                                      -86.17401
institution_control_label              Private nonprofit
institution_control_order                              2
campus_status_label                          Main campus
admission_rate_status                        Unavailable
region_label                                   Southeast
region_order                                           5
locale_type_label                                   City
locale_detailed_label                      City: Midsize
locale_detailed_order                                  2
undergraduate_enrollment_primary                     241
undergraduate_enrollment_size_band      Fewer than 1,000
Name: 2, dtype: object



3
UNITID                                                             100706
INSTNM                                University of Alabama in Huntsville
CITY                                                           Huntsville
STABBR                                                                 AL
ZIP                                                                 35899
city_state_label                                           Huntsville, AL
LATITUDE                                                        34.724557
LONGITUDE                                                      -86.640449
institution_control_label                                          Public
institution_control_order                                               1
campus_status_label                                           Main campus
admission_rate_status                                           Available
region_label                                                    Southeast
region_order                                                            5
locale_type_label                                                    City
locale_detailed_label                                       City: Midsize
locale_detailed_order                                                   2
undergraduate_enrollment_primary                                     6591
undergraduate_enrollment_size_band                         5,000 to 9,999
Name: 3, dtype: object



4
UNITID                                                  100724
INSTNM                                Alabama State University
CITY                                                Montgomery
STABBR                                                      AL
ZIP                                                 36104-0271
city_state_label                                Montgomery, AL
LATITUDE                                             32.364317
LONGITUDE                                           -86.295677
institution_control_label                               Public
institution_control_order                                    1
campus_status_label                                Main campus
admission_rate_status                                Available
region_label                                         Southeast
region_order                                                 5
locale_type_label                                         City
locale_detailed_label                            City: Midsize
locale_detailed_order                                        2
undergraduate_enrollment_primary                          3477
undergraduate_enrollment_size_band              1,000 to 4,999
Name: 4, dtype: object



5
UNITID                                                   100751
INSTNM                                The University of Alabama
CITY                                                 Tuscaloosa
STABBR                                                       AL
ZIP                                                  35487-0100
city_state_label                                 Tuscaloosa, AL
LATITUDE                                              33.211875
LONGITUDE                                            -87.545978
institution_control_label                                Public
institution_control_order                                     1
campus_status_label                                 Main campus
admission_rate_status                                 Available
region_label                                          Southeast
region_order                                                  5
locale_type_label                                          City
locale_detailed_label                             City: Midsize
locale_detailed_order                                         2
undergraduate_enrollment_primary                          33227
undergraduate_enrollment_size_band               20,000 or more
Name: 5, dtype: object



6
UNITID                                                 100812
INSTNM                                Athens State University
CITY                                                   Athens
STABBR                                                     AL
ZIP                                                     35611
city_state_label                                   Athens, AL
LATITUDE                                            34.806793
LONGITUDE                                          -86.964698
institution_control_label                              Public
institution_control_order                                   1
campus_status_label                               Main campus
admission_rate_status                             Unavailable
region_label                                        Southeast
region_order                                                5
locale_type_label                                        Town
locale_detailed_label                            Town: Fringe
locale_detailed_order                                       7
undergraduate_enrollment_primary                         2446
undergraduate_enrollment_size_band             1,000 to 4,999
Name: 6, dtype: object



7
UNITID                                                         100830
INSTNM                                Auburn University at Montgomery
CITY                                                       Montgomery
STABBR                                                             AL
ZIP                                                        36117-3596
city_state_label                                       Montgomery, AL
LATITUDE                                                     32.36736
LONGITUDE                                                  -86.177544
institution_control_label                                      Public
institution_control_order                                           1
campus_status_label                                       Main campus
admission_rate_status                                       Available
region_label                                                Southeast
region_order                                                        5
locale_type_label                                                City
locale_detailed_label                                   City: Midsize
locale_detailed_order                                               2
undergraduate_enrollment_primary                                 2542
undergraduate_enrollment_size_band                     1,000 to 4,999
Name: 7, dtype: object



8
UNITID                                           100858
INSTNM                                Auburn University
CITY                                             Auburn
STABBR                                               AL
ZIP                                               36849
city_state_label                             Auburn, AL
LATITUDE                                      32.599378
LONGITUDE                                    -85.488258
institution_control_label                        Public
institution_control_order                             1
campus_status_label                         Main campus
admission_rate_status                         Available
region_label                                  Southeast
region_order                                          5
locale_type_label                                  City
locale_detailed_label                       City: Small
locale_detailed_order                                 3
undergraduate_enrollment_primary                  26816
undergraduate_enrollment_size_band       20,000 or more
Name: 8, dtype: object



9
UNITID                                                     101116
INSTNM                                South University-Montgomery
CITY                                                   Montgomery
STABBR                                                         AL
ZIP                                                         36116
city_state_label                                   Montgomery, AL
LATITUDE                                                32.342684
LONGITUDE                                              -86.216488
institution_control_label                      Private for-profit
institution_control_order                                       3
campus_status_label                               Non-main campus
admission_rate_status                                 Unavailable
region_label                                            Southeast
region_order                                                    5
locale_type_label                                            City
locale_detailed_label                               City: Midsize
locale_detailed_order                                           2
undergraduate_enrollment_primary                              299
undergraduate_enrollment_size_band               Fewer than 1,000
Name: 9, dtype: object



10
UNITID                                             101189
INSTNM                                Faulkner University
CITY                                           Montgomery
STABBR                                                 AL
ZIP                                            36109-3390
city_state_label                           Montgomery, AL
LATITUDE                                        32.384181
LONGITUDE                                       -86.21641
institution_control_label               Private nonprofit
institution_control_order                               2
campus_status_label                           Main campus
admission_rate_status                           Available
region_label                                    Southeast
region_order                                            5
locale_type_label                                    City
locale_detailed_label                       City: Midsize
locale_detailed_order                                   2
undergraduate_enrollment_primary                     1549
undergraduate_enrollment_size_band         1,000 to 4,999
Name: 10, dtype: object



11
UNITID                                            101435
INSTNM                                Huntingdon College
CITY                                          Montgomery
STABBR                                                AL
ZIP                                           36106-2148
city_state_label                          Montgomery, AL
LATITUDE                                       32.351034
LONGITUDE                                     -86.284366
institution_control_label              Private nonprofit
institution_control_order                              2
campus_status_label                          Main campus
admission_rate_status                          Available
region_label                                   Southeast
region_order                                           5
locale_type_label                                   City
locale_detailed_label                      City: Midsize
locale_detailed_order                                  2
undergraduate_enrollment_primary                     879
undergraduate_enrollment_size_band      Fewer than 1,000
Name: 11, dtype: object



12
UNITID                                                       101453
INSTNM                                Heritage Christian University
CITY                                                       Florence
STABBR                                                           AL
ZIP                                                      35630-9977
city_state_label                                       Florence, AL
LATITUDE                                                  34.856153
LONGITUDE                                                -87.663051
institution_control_label                         Private nonprofit
institution_control_order                                         2
campus_status_label                                     Main campus
admission_rate_status                                     Available
region_label                                              Southeast
region_order                                                      5
locale_type_label                                              City
locale_detailed_label                                   City: Small
locale_detailed_order                                             3
undergraduate_enrollment_primary                                 75
undergraduate_enrollment_size_band                 Fewer than 1,000
Name: 12, dtype: object



13
UNITID                                                       101480
INSTNM                                Jacksonville State University
CITY                                                   Jacksonville
STABBR                                                           AL
ZIP                                                           36265
city_state_label                                   Jacksonville, AL
LATITUDE                                                  33.822938
LONGITUDE                                                -85.765321
institution_control_label                                    Public
institution_control_order                                         1
campus_status_label                                     Main campus
admission_rate_status                                     Available
region_label                                              Southeast
region_order                                                      5
locale_type_label                                            Suburb
locale_detailed_label                                 Suburb: Small
locale_detailed_order                                             6
undergraduate_enrollment_primary                               7036
undergraduate_enrollment_size_band                   5,000 to 9,999
Name: 13, dtype: object



14
UNITID                                                    101587
INSTNM                                University of West Alabama
CITY                                                  Livingston
STABBR                                                        AL
ZIP                                                        35470
city_state_label                                  Livingston, AL
LATITUDE                                               32.588132
LONGITUDE                                             -88.186329
institution_control_label                                 Public
institution_control_order                                      1
campus_status_label                                  Main campus
admission_rate_status                                  Available
region_label                                           Southeast
region_order                                                   5
locale_type_label                                          Rural
locale_detailed_label                              Rural: Remote
locale_detailed_order                                         12
undergraduate_enrollment_primary                            2974
undergraduate_enrollment_size_band                1,000 to 4,999
Name: 14, dtype: object



15
UNITID                                           101675
INSTNM                                    Miles College
CITY                                          Fairfield
STABBR                                               AL
ZIP                                          35064-2621
city_state_label                          Fairfield, AL
LATITUDE                                      33.482442
LONGITUDE                                    -86.908751
institution_control_label             Private nonprofit
institution_control_order                             2
campus_status_label                         Main campus
admission_rate_status                       Unavailable
region_label                                  Southeast
region_order                                          5
locale_type_label                                Suburb
locale_detailed_label                     Suburb: Large
locale_detailed_order                                 4
undergraduate_enrollment_primary                   1155
undergraduate_enrollment_size_band       1,000 to 4,999
Name: 15, dtype: object



16
UNITID                                              101693
INSTNM                                University of Mobile

In [17]:
# Filtering dataframe using columns
data.loc[data['admission_rate_status'] == 'Available', ['UNITID', 'CITY', 'ZIP']][0:10]

    UNITID        CITY         ZIP
0   100654      Normal       35762
1   100663  Birmingham  35294-0110
3   100706  Huntsville       35899
4   100724  Montgomery  36104-0271
5   100751  Tuscaloosa  35487-0100
7   100830  Montgomery  36117-3596
8   100858      Auburn       36849
10  101189  Montgomery  36109-3390
11  101435  Montgomery  36106-2148
12  101453    Florence  35630-9977

In [18]:
# Filtering dataframe using contains keyword
data[data['CITY'].str.contains('Mont')]

,UNITID,INSTNM,CITY,STABBR,ZIP,city_state_label,LATITUDE,LONGITUDE,institution_control_label,institution_control_order,campus_status_label,admission_rate_status,region_label,region_order,locale_type_label,locale_detailed_label,locale_detailed_order,undergraduate_enrollment_primary,undergraduate_enrollment_size_band
2,100690,Amridge University,Montgomery,AL,36117-3553,"Montgomery, AL",32.362609,-86.174010,Private nonprofit,2,Main campus,Unavailable,Southeast,5,City,City: Midsize,2,241,"Fewer than 1,000"
4,100724,Alabama State University,Montgomery,AL,36104-0271,"Montgomery, AL",32.364317,-86.295677,Public,1,Main campus,Available,Southeast,5,City,City: Midsize,2,3477,"1,000 to 4,999"
7,100830,Auburn University at Montgomery,Montgomery,AL,36117-3596,"Montgomery, AL",32.367360,-86.177544,Public,1,Main campus,Available,Southeast,5,City,City: Midsize,2,2542,"1,000 to 4,999"
9,101116,South University-Montgomery,Montgomery,AL,36116,"Montgomery, AL",32.342684,-86.216488,Private for-profit,3,Non-main campus,Unavailable,Southeast,5,City,City: Midsize,2,299,"Fewer than 1,000"
10,101189,Faulkner University,Montgomery,AL,36109-3390,"Montgomery, AL",32.384181,-86.216410,Private nonprofit,2,Main campus,Available,Southeast,5,City,City: Midsize,2,1549,"1,000 to 4,999"
11,101435,Huntingdon College,Montgomery,AL,36106-2148,"Montgomery, AL",32.351034,-86.284366,Private nonprofit,2,Main campus,Available,Southeast,5,City,City: Midsize,2,879,"Fewer than 1,000"
17,101709,University of Montevallo,Montevallo,AL,35115-6000,"Montevallo, AL",33.106250,-86.865099,Public,1,Main campus,Available,Southeast,5,Town,Town: Fringe,7,2151,"1,000 to 4,999"
118,119058,Middlebury Institute of International Studies ...,Monterey,CA,93940,"Monterey, CA",36.599736,-121.897325,Private nonprofit,2,Non-main campus,Unavailable,Far West,8,Suburb,Suburb: Midsize,5,4,"Fewer than 1,000"
845,185590,Montclair State University,Montclair,NJ,07043-1624,"Montclair, NJ",40.860414,-74.198141,Public,1,Main campus,Available,Mid East,2,Suburb,Suburb: Large,4,18376,"10,000 to 19,999"
1034,199032,Montreat College,Montreat,NC,28757-1267,"Montreat, NC",35.646577,-82.297600,Private nonprofit,2,Main campus,Available,Southeast,5,Suburb,Suburb: Large,4,762,"Fewer than 1,000"
1257,214795,Pennsylvania State University-Penn State Mont ...,Mont Alto,PA,17237-9700,"Mont Alto, PA",39.842212,-77.541797,Public,1,Non-main campus,Available,Mid East,2,Rural,Rural: Fringe,10,559,"Fewer than 1,000"

In [19]:
# Using query function
data.query('INSTNM == "University of Montevallo"')

,UNITID,INSTNM,CITY,STABBR,ZIP,city_state_label,LATITUDE,LONGITUDE,institution_control_label,institution_control_order,campus_status_label,admission_rate_status,region_label,region_order,locale_type_label,locale_detailed_label,locale_detailed_order,undergraduate_enrollment_primary,undergraduate_enrollment_size_band
17,101709,University of Montevallo,Montevallo,AL,35115-6000,"Montevallo, AL",33.10625,-86.865099,Public,1,Main campus,Available,Southeast,5,Town,Town: Fringe,7,2151,"1,000 to 4,999"

#### Add/Remove column

In [20]:
# Adding a new column
data['NewColumn'] = 'Aranya'

In [21]:
# Dropping a column
data.drop(data['region_order'], inplace=True)

In [22]:
data.head()

,UNITID,INSTNM,CITY,STABBR,ZIP,city_state_label,LATITUDE,LONGITUDE,institution_control_label,institution_control_order,campus_status_label,admission_rate_status,region_label,region_order,locale_type_label,locale_detailed_label,locale_detailed_order,undergraduate_enrollment_primary,undergraduate_enrollment_size_band,NewColumn
0,100654,Alabama A & M University,Normal,AL,35762,"Normal, AL",34.783368,-86.568502,Public,1,Main campus,Available,Southeast,5,City,City: Midsize,2,6124,"5,000 to 9,999",Aranya
11,101435,Huntingdon College,Montgomery,AL,36106-2148,"Montgomery, AL",32.351034,-86.284366,Private nonprofit,2,Main campus,Available,Southeast,5,City,City: Midsize,2,879,"Fewer than 1,000",Aranya
12,101453,Heritage Christian University,Florence,AL,35630-9977,"Florence, AL",34.856153,-87.663051,Private nonprofit,2,Main campus,Available,Southeast,5,City,City: Small,3,75,"Fewer than 1,000",Aranya
13,101480,Jacksonville State University,Jacksonville,AL,36265,"Jacksonville, AL",33.822938,-85.765321,Public,1,Main campus,Available,Southeast,5,Suburb,Suburb: Small,6,7036,"5,000 to 9,999",Aranya
14,101587,University of West Alabama,Livingston,AL,35470,"Livingston, AL",32.588132,-88.186329,Public,1,Main campus,Available,Southeast,5,Rural,Rural: Remote,12,2974,"1,000 to 4,999",Aranya

In [23]:
# Renaming a column
data.rename(columns={'ZIP':'Zip_Code'})

,UNITID,INSTNM,CITY,STABBR,Zip_Code,city_state_label,LATITUDE,LONGITUDE,institution_control_label,institution_control_order,campus_status_label,admission_rate_status,region_label,region_order,locale_type_label,locale_detailed_label,locale_detailed_order,undergraduate_enrollment_primary,undergraduate_enrollment_size_band,NewColumn
0,100654,Alabama A & M University,Normal,AL,35762,"Normal, AL",34.783368,-86.568502,Public,1,Main campus,Available,Southeast,5,City,City: Midsize,2,6124,"5,000 to 9,999",Aranya
11,101435,Huntingdon College,Montgomery,AL,36106-2148,"Montgomery, AL",32.351034,-86.284366,Private nonprofit,2,Main campus,Available,Southeast,5,City,City: Midsize,2,879,"Fewer than 1,000",Aranya
12,101453,Heritage Christian University,Florence,AL,35630-9977,"Florence, AL",34.856153,-87.663051,Private nonprofit,2,Main campus,Available,Southeast,5,City,City: Small,3,75,"Fewer than 1,000",Aranya
13,101480,Jacksonville State University,Jacksonville,AL,36265,"Jacksonville, AL",33.822938,-85.765321,Public,1,Main campus,Available,Southeast,5,Suburb,Suburb: Small,6,7036,"5,000 to 9,999",Aranya
14,101587,University of West Alabama,Livingston,AL,35470,"Livingston, AL",32.588132,-88.186329,Public,1,Main campus,Available,Southeast,5,Rural,Rural: Remote,12,2974,"1,000 to 4,999",Aranya
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1929,499422,Denver College of Nursing-Houston,Houston,TX,77079-3021,"Houston, TX",29.781312,-95.607143,Private for-profit,3,Non-main campus,Unavailable,Southwest,6,City,City: Large,1,135,"Fewer than 1,000",Aranya
1930,500290,Arizona College of Nursing - Chesapeake,Chesapeake,VA,23320-4686,"Chesapeake, VA",36.768088,-76.240372,Private for-profit,3,Non-main campus,Available,Southeast,5,City,City: Large,1,149,"Fewer than 1,000",Aranya
1931,500306,Arizona College of Nursing - Hartford,East Hartford,CT,06108-3288,"East Hartford, CT",41.768617,-72.662653,Private for-profit,3,Non-main campus,Available,New England,1,City,City: Small,3,334,"Fewer than 1,000",Aranya
1932,500333,Arizona College of Nursing-St Louis,Maryland Heights,MO,63146-4011,"Maryland Heights, MO",38.690785,-90.449253,Private for-profit,3,Non-main campus,Available,Plains,4,Suburb,Suburb: Large,4,131,"Fewer than 1,000",Aranya
1933,500342,EDvance College,San Francisco,CA,94104,"San Francisco, CA",37.789663,-122.401480,Private nonprofit,2,Non-main campus,Available,Far West,8,City,City: Large,1,201,"Fewer than 1,000",Aranya

In [24]:
# Dropping a column
data.drop(columns='NewColumn')

,UNITID,INSTNM,CITY,STABBR,ZIP,city_state_label,LATITUDE,LONGITUDE,institution_control_label,institution_control_order,campus_status_label,admission_rate_status,region_label,region_order,locale_type_label,locale_detailed_label,locale_detailed_order,undergraduate_enrollment_primary,undergraduate_enrollment_size_band
0,100654,Alabama A & M University,Normal,AL,35762,"Normal, AL",34.783368,-86.568502,Public,1,Main campus,Available,Southeast,5,City,City: Midsize,2,6124,"5,000 to 9,999"
11,101435,Huntingdon College,Montgomery,AL,36106-2148,"Montgomery, AL",32.351034,-86.284366,Private nonprofit,2,Main campus,Available,Southeast,5,City,City: Midsize,2,879,"Fewer than 1,000"
12,101453,Heritage Christian University,Florence,AL,35630-9977,"Florence, AL",34.856153,-87.663051,Private nonprofit,2,Main campus,Available,Southeast,5,City,City: Small,3,75,"Fewer than 1,000"
13,101480,Jacksonville State University,Jacksonville,AL,36265,"Jacksonville, AL",33.822938,-85.765321,Public,1,Main campus,Available,Southeast,5,Suburb,Suburb: Small,6,7036,"5,000 to 9,999"
14,101587,University of West Alabama,Livingston,AL,35470,"Livingston, AL",32.588132,-88.186329,Public,1,Main campus,Available,Southeast,5,Rural,Rural: Remote,12,2974,"1,000 to 4,999"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1929,499422,Denver College of Nursing-Houston,Houston,TX,77079-3021,"Houston, TX",29.781312,-95.607143,Private for-profit,3,Non-main campus,Unavailable,Southwest,6,City,City: Large,1,135,"Fewer than 1,000"
1930,500290,Arizona College of Nursing - Chesapeake,Chesapeake,VA,23320-4686,"Chesapeake, VA",36.768088,-76.240372,Private for-profit,3,Non-main campus,Available,Southeast,5,City,City: Large,1,149,"Fewer than 1,000"
1931,500306,Arizona College of Nursing - Hartford,East Hartford,CT,06108-3288,"East Hartford, CT",41.768617,-72.662653,Private for-profit,3,Non-main campus,Available,New England,1,City,City: Small,3,334,"Fewer than 1,000"
1932,500333,Arizona College of Nursing-St Louis,Maryland Heights,MO,63146-4011,"Maryland Heights, MO",38.690785,-90.449253,Private for-profit,3,Non-main campus,Available,Plains,4,Suburb,Suburb: Large,4,131,"Fewer than 1,000"
1933,500342,EDvance College,San Francisco,CA,94104,"San Francisco, CA",37.789663,-122.401480,Private nonprofit,2,Non-main campus,Available,Far West,8,City,City: Large,1,201,"Fewer than 1,000"

In [25]:
# Adding new column with string function
data['College_First_Part'] = data['INSTNM'].str.split(' ').str[0]

In [26]:
data['College_First_Part']

0            Alabama
11        Huntingdon
12          Heritage
13      Jacksonville
14        University
            ...
1929          Denver
1930         Arizona
1931         Arizona
1932         Arizona
1933         EDvance
Name: College_First_Part, Length: 1924, dtype: object

In [27]:
data.head()

,UNITID,INSTNM,CITY,STABBR,ZIP,city_state_label,LATITUDE,LONGITUDE,institution_control_label,institution_control_order,...,admission_rate_status,region_label,region_order,locale_type_label,locale_detailed_label,locale_detailed_order,undergraduate_enrollment_primary,undergraduate_enrollment_size_band,NewColumn,College_First_Part
0,100654,Alabama A & M University,Normal,AL,35762,"Normal, AL",34.783368,-86.568502,Public,1,...,Available,Southeast,5,City,City: Midsize,2,6124,"5,000 to 9,999",Aranya,Alabama
11,101435,Huntingdon College,Montgomery,AL,36106-2148,"Montgomery, AL",32.351034,-86.284366,Private nonprofit,2,...,Available,Southeast,5,City,City: Midsize,2,879,"Fewer than 1,000",Aranya,Huntingdon
12,101453,Heritage Christian University,Florence,AL,35630-9977,"Florence, AL",34.856153,-87.663051,Private nonprofit,2,...,Available,Southeast,5,City,City: Small,3,75,"Fewer than 1,000",Aranya,Heritage
13,101480,Jacksonville State University,Jacksonville,AL,36265,"Jacksonville, AL",33.822938,-85.765321,Public,1,...,Available,Southeast,5,Suburb,Suburb: Small,6,7036,"5,000 to 9,999",Aranya,Jacksonville
14,101587,University of West Alabama,Livingston,AL,35470,"Livingston, AL",32.588132,-88.186329,Public,1,...,Available,Southeast,5,Rural,Rural: Remote,12,2974,"1,000 to 4,999",Aranya,University

In [28]:
# Adding a custom column with evalution
data['Enrollment_Category']= data['undergraduate_enrollment_primary'].apply(lambda x: 'low' if x < 500 else ('medium' if x<=5000 else 'high'))

In [29]:
data.head()

,UNITID,INSTNM,CITY,STABBR,ZIP,city_state_label,LATITUDE,LONGITUDE,institution_control_label,institution_control_order,...,region_label,region_order,locale_type_label,locale_detailed_label,locale_detailed_order,undergraduate_enrollment_primary,undergraduate_enrollment_size_band,NewColumn,College_First_Part,Enrollment_Category
0,100654,Alabama A & M University,Normal,AL,35762,"Normal, AL",34.783368,-86.568502,Public,1,...,Southeast,5,City,City: Midsize,2,6124,"5,000 to 9,999",Aranya,Alabama,high
11,101435,Huntingdon College,Montgomery,AL,36106-2148,"Montgomery, AL",32.351034,-86.284366,Private nonprofit,2,...,Southeast,5,City,City: Midsize,2,879,"Fewer than 1,000",Aranya,Huntingdon,medium
12,101453,Heritage Christian University,Florence,AL,35630-9977,"Florence, AL",34.856153,-87.663051,Private nonprofit,2,...,Southeast,5,City,City: Small,3,75,"Fewer than 1,000",Aranya,Heritage,low
13,101480,Jacksonville State University,Jacksonville,AL,36265,"Jacksonville, AL",33.822938,-85.765321,Public,1,...,Southeast,5,Suburb,Suburb: Small,6,7036,"5,000 to 9,999",Aranya,Jacksonville,high
14,101587,University of West Alabama,Livingston,AL,35470,"Livingston, AL",32.588132,-88.186329,Public,1,...,Southeast,5,Rural,Rural: Remote,12,2974,"1,000 to 4,999",Aranya,University,medium

#### Aggregating data

In [30]:
# Returing the count of uniques values of a column
data['Enrollment_Category'].value_counts()

Enrollment_Category
medium    1080
high       432
low        412
Name: count, dtype: int64

In [31]:
# Grouping by State 
data.groupby(['STABBR'])['INSTNM'].count()

STABBR
AK      3
AL     21
AR     23
AZ     22
CA    147
CO     23
CT     27
DC     10
DE      5
FL     66
GA     55
GU      1
HI      7
IA     32
ID     10
IL     69
IN     46
KS     28
KY     30
LA     29
MA     71
MD     32
ME     17
MI     46
MN     40
MO     54
MS     17
MT     10
NC     60
ND      9
NE     21
NH     13
NJ     49
NM     10
NV      8
NY    166
OH     77
OK     24
OR     25
PA    117
PR     39
RI     11
SC     36
SD     12
TN     44
TX    101
UT     13
VA     53
VI      1
VT      8
WA     29
WI     36
WV     20
WY      1
Name: INSTNM, dtype: int64

In [32]:
# Using aggregate groupby
data.groupby(['STABBR']).agg({'undergraduate_enrollment_primary': sum, 'region_order': sum})

        undergraduate_enrollment_primary  region_order
STABBR
AK                                 11443            24
AL                                 70006           105
AR                                 73010           115
AZ                                381857           132
CA                                848631          1176
CO                                171149           164
CT                                108733            36
DC                                 51071            20
DE                                 32227            10
FL                                418081           330
GA                                304818           275
GU                                  2515             9
HI                                 26790            56
IA                                 88991           128
ID                                 38703            70
IL                                254545           207
IN                                202076           138
KS                                 82199           112
KY                                118016           150
LA                                124444           145
MA                                241056            71
MD                                166510            72
ME                                 39626            17
MI                                234440           138
MN                                146613           160
MO                                143324           216
MS                                 70821            85
MT                                 30488            70
NC                                250755           300
ND                                 27893            36
NE                                 64995            84
NH                                192618            13
NJ                                188405            98
NM                                 38609            60
NV                                 46416            64
NY                                569280           348
OH                                280244           231
OK                                 93694           144
OR                                 93336           200
PA                                350193           234
PR                                 88336           351
RI                                 47791            11
SC                                127848           180
SD                                 27376            48
TN                                156457           220
TX                                649253           606
UT                                253680            91
VA                                263182           265
VI                                  1518             9
VT                                 25173             8
WA                                118038           232
WI                                154473           108
WV                                 83626           100
WY                                  7944             7

#### Advanced Functionality

In [33]:
# Ranking data based on a column
data['Ranked_LATITUDE'] = data['LATITUDE'].rank()

In [34]:
# Ranking data based on ranked result
data.sort_values(['Ranked_LATITUDE'], ascending=False)

,UNITID,INSTNM,CITY,STABBR,ZIP,city_state_label,LATITUDE,LONGITUDE,institution_control_label,institution_control_order,...,region_order,locale_type_label,locale_detailed_label,locale_detailed_order,undergraduate_enrollment_primary,undergraduate_enrollment_size_band,NewColumn,College_First_Part,Enrollment_Category,Ranked_LATITUDE
31,102614,University of Alaska Fairbanks,Fairbanks,AK,99775,"Fairbanks, AK",64.857560,-147.823146,Public,1,...,8,City,City: Small,3,4207,"1,000 to 4,999",Aranya,University,medium,1924.0
30,102580,Alaska Bible College,Palmer,AK,99645,"Palmer, AK",61.598553,-149.111972,Private nonprofit,2,...,8,Suburb,Suburb: Small,6,24,"Fewer than 1,000",Aranya,Alaska,low,1923.0
29,102553,University of Alaska Anchorage,Anchorage,AK,99508,"Anchorage, AK",61.190163,-149.826190,Public,1,...,8,City,City: Large,1,7212,"5,000 to 9,999",Aranya,University,high,1922.0
1541,237011,Western Washington University,Bellingham,WA,98225-9008,"Bellingham, WA",48.737812,-122.485734,Public,1,...,8,City,City: Small,3,13544,"10,000 to 19,999",Aranya,Western,high,1921.0
792,180522,Montana State University-Northern,Havre,MT,59501,"Havre, MT",48.541490,-109.687806,Public,1,...,7,Town,Town: Remote,9,761,"Fewer than 1,000",Aranya,Montana,medium,1920.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1611,242662,Inter American University of Puerto Rico-Ponce,Mercedita,PR,00715-1602,"Mercedita, PR",18.007388,-66.578498,Private nonprofit,2,...,9,Rural,Rural: Fringe,10,2404,"1,000 to 4,999",Aranya,Inter,medium,5.0
1646,363907,Caribbean University-Ponce,Ponce,PR,00716-7733,"Ponce, PR",18.006633,-66.594250,Private nonprofit,2,...,9,City,City: Midsize,2,414,"Fewer than 1,000",Aranya,Caribbean,low,4.0
1601,241410,Pontifical Catholic University of Puerto Rico-...,Ponce,PR,00717-9997,"Ponce, PR",18.001650,-66.617138,Private nonprofit,2,...,9,City,City: Midsize,2,3874,"1,000 to 4,999",Aranya,Pontifical,medium,3.0
1622,243212,University of Puerto Rico at Ponce,Ponce,PR,00716-9996,"Ponce, PR",17.993314,-66.606215,Public,1,...,9,City,City: Midsize,2,2278,"1,000 to 4,999",Aranya,University,medium,2.0
1594,240754,University of Guam,Mangilao,GU,96923,"Mangilao, GU",13.433047,144.803978,Public,1,...,9,Suburb,Suburb: Midsize,5,2515,"1,000 to 4,999",Aranya,University,medium,1.0

In [35]:
# Using cumilative sum
data['cumilative_region_order'] = data['region_order'].cumsum()

In [36]:
data.head(3)

,UNITID,INSTNM,CITY,STABBR,ZIP,city_state_label,LATITUDE,LONGITUDE,institution_control_label,institution_control_order,...,locale_type_label,locale_detailed_label,locale_detailed_order,undergraduate_enrollment_primary,undergraduate_enrollment_size_band,NewColumn,College_First_Part,Enrollment_Category,Ranked_LATITUDE,cumilative_region_order
0,100654,Alabama A & M University,Normal,AL,35762,"Normal, AL",34.783368,-86.568502,Public,1,...,City,City: Midsize,2,6124,"5,000 to 9,999",Aranya,Alabama,high,497.0,5
11,101435,Huntingdon College,Montgomery,AL,36106-2148,"Montgomery, AL",32.351034,-86.284366,Private nonprofit,2,...,City,City: Midsize,2,879,"Fewer than 1,000",Aranya,Huntingdon,medium,222.0,10
12,101453,Heritage Christian University,Florence,AL,35630-9977,"Florence, AL",34.856153,-87.663051,Private nonprofit,2,...,City,City: Small,3,75,"Fewer than 1,000",Aranya,Heritage,low,500.0,15